### ISSUE TITLE
[features  request]add support typedef ?

### ISSUE THREAD

**Issue by sonygod** [HeapsIO/hxbit#42]
[features  request  ]add support typedef?

**Comment by ncannasse** [comment]
we already support typedefs.

**Comment by sonygod** [comment]
you mean like this

import hxbit.*;

   @:s typedef Player ={
	var name:String;
	var age:Int;
  } 

 it's seem not work.

**Comment by ncannasse** [comment]
I think this works already without this @:s for typedef Player.

**Comment by sonygod** [comment]
@ncannasse  can you give a small example? api like  

      var s = new Serializer();

     s.serialize{{age: 1,name: "test"});//current version it's error.

**Comment by ncannasse** [comment]
It's not possible because a typedef can't hold any method or metadata
necessary for hxbit serialization.
