### ISSUE TITLE
float error.

### ISSUE THREAD

**Issue by sonygod** [HeapsIO/hxbit#43]
package;

	import hxbit.*;

	class User implements hxbit.Serializable {
		@:s public var date: Float;
	   
		public function new(){
			
		}
	   
	   
	}

	 
	class Main 
	{
		
		static function main() 
		{
			var s = new hxbit.Serializer();
			var u = new User();
			
			
			var now = Date.now().getTime();
			u.date = now;
			trace(now);
			
			
		
			var xx = s.serialize(u);
			
			
			
			var u = new hxbit.Serializer();
			
			var yy = u.unserialize(xx,User);
			
			
			trace(yy.date);
			
			trace(yy.date==now);//false
			
			
		}
		
	}

**Comment by ncannasse** [comment]
This is because by default we use single precision for serialization.
