### ISSUE TITLE
Serialization without including UID

### ISSUE THREAD

**Issue by kyubuns** [HeapsIO/hxbit#49]
This is a feature request, but I'd like to hear the producers' thoughts first.

hxbit is amazing.
I'm trying to use hxbit for the structure of the save data and system data.
Because the serialized data contains UIDs, we are having the following problems

- Make my save data bigger
- I can't use it to verify that the data matches

So I want a serialization that does not include UID.

**Comment by ncannasse** [comment]
Interesting but not easy to add :)

**Comment by kyubuns** [comment]
Agree with you, I solved it by skipping compatibility and made special revision for this.
https://github.com/kyubuns/hxbitmini
