### ISSUE TITLE
Executing method on unserializing attribute

### ISSUE THREAD

**Issue by olichose123** [HeapsIO/hxbit#53]
I have serializable **Models** and json-loaded **Definitions**. I use a serializable **Reference** object to point to a Definition class and a name. When I initialize the Reference, it fetches the Definition from a name. 

Usually, I'd keep an array of references and initialize them all when everything is loaded. Unfortunately, when I unserialize Models which contain References, I cannot know that the Reference was unserialized and, since the constructor was not called, I cannot add it to a static array of references.

How would I call a method on a certain type of object when it is unserialized if this object is serialized as part of another object?

I thought serializer.unserialize(instance) was called on every child object but I discovered with a custom serializer that it is not the case. 
I cannot seem to override methods added by hxbit.Serializable, though I haven't tried with macros.

Pseudocode
```
class Reference<T>
  static all:Array<Reference>
  @:s name:String
  @:s className:String
  value:T
  function initialize()
    return MyDefinition.all.get(this.name) // using reflection

class MyDefinition extends Definition
  static all:StringMap<MyDefinition>
  name:Int
  x:Int
  y:Int

class MyModel extends Model
  @:s myDef:Reference<MyDefinition>
```
**Objective**
unserialize a MyModel instance, which also unserializes a Reference instance
call initialize() on the Reference instance, or simply store it in Reference.all for subsequent handling

**Constraints**
While I understand that if MyDefinition was serialized, this would remove the need for a Reference object, in this specific case the feel needs to be json-loaded as it might change. Unserialized Models need to access up to date Definition data at any time.

**Comment by olichose123** [comment]
Looks like a simple macro is a solution. Though some kind of callback would be a better approach. Hell, why not a macro-based callback assignator.

```
macro public static function build():Array<Field>
	{
		// Initial fields get
		var fields = Context.getBuildFields();
		var type = Context.toComplexType(Context.getLocalType());

		// find unserialize function
		var unserialize:Field = null;

		// find constructor
		for (field in fields)
		{
			if (field.name == 'unserialize')
			{
				unserialize = field;
				break;
			}
		}

		// add expr
		switch (unserialize.kind)
		{
			case FFun(f):
				f.expr = macro $b
					{
						[
							macro
							{
								Reference.all.push(this);
							},
							f.expr
						]
					}
			case _:
				throw 'should not happen';
		}

		// return fields
		return fields;
	}
}
```

**Comment by olichose123** [comment]
So, I think serializables should have macro-generated functions `beforeSerialize`, `afterSerialize`, `beforeUnserialize`, `afterUnserialize` which a user could assign a value to. They could be dynamic, but I'm not sure if haxe handles overriden dynamic functions or if it can't be both at the same time.

To simplify, maybe a simple `onSerialize` and `onUnserialize` after the fact would suffice.

**Comment by ncannasse** [comment]
You can override serialize and unserialize methods for this. Make sure to
call super.serialize() to tell where the serialize code should be inserted.

Le dim. 1 nov. 2020 à 23:35, Olivier Banville <notifications@github.com> a
écrit :

**Comment by olichose123** [comment]
It seems I cannot override serialize() or unserialize() in the class that implements hxbit.Serializable, but I can in children classes.
For a simple class:
```haxe
class M implements hxbit.Serializable
{
    override public function unserialize(ctx:Serializer):Void
    {
        super(ctx);
    }
}
```
I get `Override of unserialize() with no super.unserialize(ctx) found`

**Comment by olichose123** [comment]
It's possible some other bug (surely caused by me) is the cause of my problems, so I'm clausing this. I've found alternatives, like lazy-initializing when accessed instead of initializing on unserialization. This'll do for now.
