### ISSUE TITLE
ArrayProxys auto-complete as Arrays

### ISSUE THREAD

**Issue by trethaller** [HeapsIO/hxbit#54]
When declaring a serializable `Array` like so:

`@:s var array : Array<Object>;`

The auto completion considers `array` to be an `Array`, while at compile-time it will become an `ArrayProxy`. This works fine as long as `ArrayProxy` implements all the same methods as `Array`, but starts to break when static extensions are added to `Array`.

For that reason (misleading auto-completion) our developers started declaring ArrayProxies specifically. This works fine, except for `length` which for some reason is marked as `@:noCompletion`. Could this be removed?

**Comment by ncannasse** [comment]
The Array/ArrayProxy is actually a feature, so completion is speedup because we skip hxbit macros processing and codegen when doing completion. 

Since I don't remember about why there's @:noCompletion on ArrayProxy I've removed it ;)
