### ISSUE TITLE
Signature mismatch due to DCE

### ISSUE THREAD

**Issue by onehundredfeet** [HeapsIO/hxbit#65]
I have a client executable and a server executable.  They both should have the same classes listed in 'registerClass'. I have added @:keep to all the classes but it still ignores them.

I have to add a dummy variable in the client for each of the missing classes in order for them to be included.  Is there a better way to do this?

**Comment by ncannasse** [comment]
You need to make sure the classes are compiled by using --macro
include("classpath")

Le mar. 7 mars 2023 à 21:29, Ryan Cleven ***@***.***> a
écrit :

**Comment by onehundredfeet** [comment]
Thanks.
