### ISSUE TITLE
Game Save State Best Practices

### ISSUE THREAD

**Issue by onehundredfeet** [HeapsIO/hxbit#68]
Do you have any recommendation for how to use this for a networked save game?

Do you typically serialize the whole world state? or a select slice? or a different structure entirely?

I use the system to send only what is needed to the client, not marked up for single player serialization.

I'm expecting to have to create a separate 'save' structure, but before I did that, I was wondering if there was a way of looking at this that I'm not familiar with.

Thanks.

**Comment by ncannasse** [comment]
We usually serialize and synchronize the whole state.

**Comment by onehundredfeet** [comment]
k thanks.
